# Generated by Django 4.1.13 on 2024-01-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='role',
            field=models.CharField(default='SWE', max_length=255),
        ),
    ]
