# Generated by Django 4.1.13 on 2024-01-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0002_experience_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='s_no',
            field=models.IntegerField(default=0),
        ),
    ]
