# Generated by Django 4.1.13 on 2024-01-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0003_experience_s_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='s_no',
            new_name='serial',
        ),
    ]
