# Generated by Django 4.1.13 on 2024-01-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0004_rename_s_no_experience_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='org',
            field=models.TextField(default='Google'),
        ),
    ]
